version: "3.9"
services:
  app:
    build:
      context: .
      target: development
    image: privacyai
    container_name: privacyai
    ports:
      - '3000:3000'
    env_file:
      - .env 
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run dev